# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dbfsplit.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 404)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sysdate_dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.sysdate_dateEdit.setMinimumDate(QtCore.QDate(1755, 9, 14))
        self.sysdate_dateEdit.setCalendarPopup(True)
        self.sysdate_dateEdit.setDate(QtCore.QDate(2016, 9, 17))
        self.sysdate_dateEdit.setObjectName("sysdate_dateEdit")
        self.horizontalLayout_2.addWidget(self.sysdate_dateEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.threadnum_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.threadnum_spinBox.setProperty("value", 50)
        self.threadnum_spinBox.setObjectName("threadnum_spinBox")
        self.horizontalLayout_2.addWidget(self.threadnum_spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.msg_label = QtWidgets.QLabel(self.centralwidget)
        self.msg_label.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.msg_label.setFont(font)
        self.msg_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.msg_label.setText("")
        self.msg_label.setObjectName("msg_label")
        self.horizontalLayout_2.addWidget(self.msg_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.task_QTableView = QtWidgets.QTableView(self.widget)
        self.task_QTableView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task_QTableView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.task_QTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.task_QTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.task_QTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.task_QTableView.setDragDropOverwriteMode(False)
        self.task_QTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.task_QTableView.setSortingEnabled(True)
        self.task_QTableView.setObjectName("task_QTableView")
        self.task_QTableView.horizontalHeader().setDefaultSectionSize(1)
        self.task_QTableView.horizontalHeader().setHighlightSections(False)
        self.task_QTableView.horizontalHeader().setMinimumSectionSize(80)
        self.task_QTableView.horizontalHeader().setSortIndicatorShown(True)
        self.task_QTableView.horizontalHeader().setStretchLastSection(True)
        self.task_QTableView.verticalHeader().setVisible(False)
        self.task_QTableView.verticalHeader().setCascadingSectionResizes(True)
        self.task_QTableView.verticalHeader().setDefaultSectionSize(0)
        self.task_QTableView.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.task_QTableView)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.run_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.run_pushButton.setObjectName("run_pushButton")
        self.horizontalLayout.addWidget(self.run_pushButton)
        self.stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.horizontalLayout.addWidget(self.stop_pushButton)
        self.exit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout.addWidget(self.exit_pushButton)
        self.select_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.select_pushButton.setObjectName("select_pushButton")
        self.horizontalLayout.addWidget(self.select_pushButton)
        self.unselect_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.unselect_pushButton.setObjectName("unselect_pushButton")
        self.horizontalLayout.addWidget(self.unselect_pushButton)
        self.reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout.addWidget(self.reset_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.newmodel_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.newmodel_checkBox.setObjectName("newmodel_checkBox")
        self.horizontalLayout.addWidget(self.newmodel_checkBox)
        self.sendok_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendok_PushButton.setObjectName("sendok_PushButton")
        self.horizontalLayout.addWidget(self.sendok_PushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "系统时间"))
        self.sysdate_dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_2.setText(_translate("MainWindow", "   线程数:"))
        self.run_pushButton.setText(_translate("MainWindow", "运行"))
        self.stop_pushButton.setText(_translate("MainWindow", "停止"))
        self.exit_pushButton.setText(_translate("MainWindow", "关闭"))
        self.select_pushButton.setText(_translate("MainWindow", "全选"))
        self.unselect_pushButton.setText(_translate("MainWindow", "全不选"))
        self.reset_pushButton.setText(_translate("MainWindow", "重置"))
        self.newmodel_checkBox.setText(_translate("MainWindow", "重新生成模板文件"))
        self.sendok_PushButton.setText(_translate("MainWindow", "OK文件"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))

